version: "3.9"

services:
  nezha:
    image: ghcr.io/nezhahq/nezha:latest
    container_name: nezha-server
    restart: always

    ports:
      - "8008:8008"  # 不可以不映射，agent需要访问它~

    volumes:
      - ./data:/dashboard/data

    environment:
      - TZ=UTC

    networks:
      - proxy   # ← 关键在这里


networks:
  proxy:
    external: true
