version: "3.9"

services:
  nezha-server:
    image: ghcr.io/naiba/nezha:latest
    container_name: nezha-server
    restart: unless-stopped
    volumes:
      - ./data:/dashboard/data
    networks:
      - proxy

networks:
  proxy:
    external: true
