version: "3.9"

services:
  nezha:
    image: ghcr.io/nezhahq/nezha:latest
    container_name: nezha-server
    restart: always

    ports:
      - "8008:8008"

    volumes:
      - /docker-compose-stacks/stacks/nezha/server/data:/dashboard/data

    environment:
      - TZ=UTC


networks:
  proxy:
    external: true
